// Country code to country name mapping
export const COUNTRY_NAMES: Record<string, string> = {
  // Popular countries
  'AE': 'United Arab Emirates',
  'US': 'United States',
  'GB': 'United Kingdom',
  'CA': 'Canada',
  'AU': 'Australia',
  'DE': 'Germany',
  'FR': 'France',
  'ES': 'Spain',
  'IT': 'Italy',
  'JP': 'Japan',
  'KR': 'South Korea',
  'CN': 'China',
  'IN': 'India',
  'BR': 'Brazil',
  'MX': 'Mexico',
  'AR': 'Argentina',
  'SA': 'Saudi Arabia',
  'EG': 'Egypt',
  'NG': 'Nigeria',
  'ZA': 'South Africa',
  'RU': 'Russia',
  'TR': 'Turkey',
  'NL': 'Netherlands',
  'BE': 'Belgium',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'SE': 'Sweden',
  'NO': 'Norway',
  'DK': 'Denmark',
  'FI': 'Finland',
  'PL': 'Poland',
  'CZ': 'Czech Republic',
  'HU': 'Hungary',
  'RO': 'Romania',
  'BG': 'Bulgaria',
  'HR': 'Croatia',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'EE': 'Estonia',
  'LV': 'Latvia',
  'LT': 'Lithuania',
  'IE': 'Ireland',
  'PT': 'Portugal',
  'GR': 'Greece',
  'CY': 'Cyprus',
  'MT': 'Malta',
  'LU': 'Luxembourg',
  'IS': 'Iceland',
  'AL': 'Albania',
  'BA': 'Bosnia and Herzegovina',
  'ME': 'Montenegro',
  'RS': 'Serbia',
  'MK': 'North Macedonia',
  'XK': 'Kosovo',
  'MD': 'Moldova',
  'UA': 'Ukraine',
  'BY': 'Belarus',
  'IL': 'Israel',
  'PS': 'Palestine',
  'JO': 'Jordan',
  'LB': 'Lebanon',
  'SY': 'Syria',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'AF': 'Afghanistan',
  'PK': 'Pakistan',
  'BD': 'Bangladesh',
  'LK': 'Sri Lanka',
  'MV': 'Maldives',
  'BT': 'Bhutan',
  'NP': 'Nepal',
  'MM': 'Myanmar',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'LA': 'Laos',
  'KH': 'Cambodia',
  'MY': 'Malaysia',
  'SG': 'Singapore',
  'BN': 'Brunei',
  'ID': 'Indonesia',
  'TL': 'Timor-Leste',
  'PH': 'Philippines',
  'TW': 'Taiwan',
  'HK': 'Hong Kong',
  'MO': 'Macao',
  'MN': 'Mongolia',
  'KZ': 'Kazakhstan',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'UZ': 'Uzbekistan',
  'TM': 'Turkmenistan',
  'AZ': 'Azerbaijan',
  'AM': 'Armenia',
  'GE': 'Georgia',
  'MA': 'Morocco',
  'DZ': 'Algeria',
  'TN': 'Tunisia',
  'LY': 'Libya',
  'SD': 'Sudan',
  'SS': 'South Sudan',
  'ET': 'Ethiopia',
  'ER': 'Eritrea',
  'DJ': 'Djibouti',
  'SO': 'Somalia',
  'KE': 'Kenya',
  'UG': 'Uganda',
  'TZ': 'Tanzania',
  'RW': 'Rwanda',
  'BI': 'Burundi',
  'CD': 'Democratic Republic of the Congo',
  'CG': 'Republic of the Congo',
  'CF': 'Central African Republic',
  'CM': 'Cameroon',
  'TD': 'Chad',
  'NE': 'Niger',
  'BF': 'Burkina Faso',
  'ML': 'Mali',
  'SN': 'Senegal',
  'GM': 'Gambia',
  'GW': 'Guinea-Bissau',
  'GN': 'Guinea',
  'SL': 'Sierra Leone',
  'LR': 'Liberia',
  'CI': 'Côte d\'Ivoire',
  'GH': 'Ghana',
  'TG': 'Togo',
  'BJ': 'Benin',
  'MR': 'Mauritania',
  'MW': 'Malawi',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'BW': 'Botswana',
  'NA': 'Namibia',
  'SZ': 'Eswatini',
  'LS': 'Lesotho',
  'MG': 'Madagascar',
  'MU': 'Mauritius',
  'SC': 'Seychelles',
  'KM': 'Comoros',
  'YT': 'Mayotte',
  'RE': 'Réunion',
  'ST': 'São Tomé and Príncipe',
  'CV': 'Cabo Verde',
  'GQ': 'Equatorial Guinea',
  'GA': 'Gabon',
  'AO': 'Angola',
  'ZZ': 'Unknown'
}

export function getCountryName(countryCode: string): string {
  return COUNTRY_NAMES[countryCode.toUpperCase()] || countryCode.toUpperCase()
}